### ISSUE TITLE
Bypassing Redis Databse Initalization

### ISSUE THREAD

**Issue by ggarcia453** [lmu-plai/xfl#5]
Hello Team. 
We are attempting to reproduce the results from your paper but are encountering issue with the pfastreXML.py file. We are specifically having a problem initializing the Redis Database. We were wondering what the purpose of the database is and whether or not it would be possible to bypass this initialization. If it is not possible to bypass this, then how should we set up the desyl.conf file so that we can avoid errors such as this one. 
We attempted to run the pfastreXML.py file from the xfl/src/ folder as below:
```
python classes/pfastreXML.py 512 dexter
```
We recieved the following error below.

``` python
Traceback (most recent call last):
  File "/media/data1/[name]/xfl/xfl/src/classes/pfastreXML.py", line 788, in <module>
    xml = PfastreXML(config, embeddings=EMBED_MODE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data1/[name]/xfl/xfl/src/classes/pfastreXML.py", line 110, in __init__
    self.exp        = classes.experiment.Experiment(config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data1/[name]/xfl/xfl/src/classes/experiment.py", line 37, in __init__
    self.rdb = classes.database.RedisDB(config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data1/[name]/xfl/xfl/src/classes/database.py", line 421, in __init__
    super().__init__(config, collection_name=collection_name)
  File "/media/data1/[name]/xfl/xfl/src/classes/database.py", line 39, in __init__
    self._db_name   = self.config.database.mongodb.name
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'mongodb'
```

We also have our desyl.conf file set up as below. 

```
{"desyl" : "", "corpus": "", "res": "/media/data1/[name]/xfl/xfl/src/res", "log2file": "", "analysis": "", "experiment": "", "database": ""}
```
Thank you.

**Comment by benoittrist** [comment]
Hi, you may be interested by the new XFL refactoring which uses no redis database.
